name: weather_hydration
description: A Flutter weather and hydration reminder app.
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: '>=2.18.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.6
  geolocator: ^9.0.2
  flutter_local_notifications: ^14.0.0

flutter:
  uses-material-design: true
